### ISSUE TITLE
have an option to change number of volumes based on input or config file

### ISSUE THREAD

**Issue by nchilaka** [gluster/glusto-tests#14]
We need to be able to change the number of volumes created/undergo test for  a specific testcase.
With gluster support for containers, we must enable glusto to start creating multiple volumes for each testcases.
Eg: in brickmux, we need to create multiple volumes for each testcase. Also we must not be hardcoding these number of volumes. Eg: I can tell glusto to create 10 or even 200 vols, and it should be able to(if the environment permits based on h/w limitations)
So we need an option or variable which can go into the config file which asks for number of vols to be created.
We must look forward to enabling glusto for scale and  not just for functional validation.
this helps in non-functional testing like checking consistency on scale.

**Comment by vavuthu** [comment]
currently, glusto doesn't have option to create "n" number of volumes based on config file.
It can be handled in test cases.
