### ISSUE TITLE
Can the 'framework' be hosted in this repo itself...

### ISSUE THREAD

**Issue by amarts** [gluster/glusto-tests#15]
## Problem statement

I am a new user, and while installing the test framework, going through the readme, I see that the `pip install` and `git clone` talks about a repo hosted by another user (not org). While it is fine to have the dependency on any repo / project, as a common user, it doesn't give me confidence to install from a user's repo.

## What is ideal?

I would like the repo to be backed by an org (like gluster.org), hosted in their github org, which can then have an infra team for managing, would follow more open guidelines about the future of the project. Ideally the user can become maintainer, and transfer the ownership to gluster org, or gluster.org can fork the repo, and keep the repo up-to-date with enhancements, and security fixes.

@loadtheaccumulator @nigelbabu @amye @mykaul @vavuthu @Akarsha-rai

**Comment by mykaul** [comment]
@loadtheaccumulator - thoughts?

**Comment by loadtheaccumulator** [comment]
> @loadtheaccumulator - thoughts?

Yeah. It was discussed in the other spaces way back, but this ticket was never closed.
The installation from the loadtheaccumulator github can be resolved via PyPi and the existing container. That was originally going to happen with Python3, but it makes sense to have the Python2 version there as well. I will make that so.

**Comment by kshithijiyer** [comment]
Ideally we can't do this as we have other project like [glusterfs-containers-tests](https://github.com/gluster/glusterfs-containers-tests) which use glusto hence it would be always better to keep it separate.
