### ISSUE TITLE
test_expanding_volume_when_io_in_progress fails intermittently

### ISSUE THREAD

**Issue by nigelbabu** [gluster/glusto-tests#2]
See:

https://ci.centos.org/view/Gluster/job/gluster_glusto/311/
https://ci.centos.org/view/Gluster/job/gluster_glusto/309/

Please let's figure out what's causing this and solve this sooner than later. Intermittent failures are unavoidable when dealing with end-to-end testing, so this is most likely due to a timeout of some sort.

**Comment by shwetha-h-p** [comment]
Taking a look @ the issue. Will update the issue on the root cause.
