### ISSUE TITLE
[RFE] Add option to control Glustr's log level through gluso-test config file

### ISSUE THREAD

**Issue by BarakSason** [gluster/glusto-tests#26]
Currently, the "log_level" field in the config file only applies to the test framework itself.
An option needs to be added which will allow to run Gluster with the specified log level.
E.g:
glusto_log_level - The log level in which glusto will run
gluster_log_level - The log level in which gluster will run

**Comment by kshithijiyer** [comment]
You can set the gluster level volume options in volume_options section of yaml file, we use the same to run for SSL.
https://github.com/gluster/glusto-tests/blob/master/tests/gluster_tests_config.yml#L216 

@BarakSason Please have a look at it and let us know if that's what you wanted to do?

**Comment by BarakSason** [comment]
@kshithijiyer Will update.

**Comment by BarakSason** [comment]
Config file seems to provide the required functionality - Closing the issue.
