### ISSUE TITLE
[RFE] Create A Centralized Logs Tar

### ISSUE THREAD

**Issue by BarakSason** [gluster/glusto-tests#28]
As logs are one of the primary tools used for analysis and debugging, adding an option which will fetch all gluster logs from all clients and servers and create a TAR of them at a given location (should be configurable, with default being the local machine) would be welcomed.

**Comment by kshithijiyer** [comment]
Ideally this is taken care in the different CIs where we run glusto-tests. We wouldn't want to collect sosreports unless we are hitting any bug. To collect sosreports while testcase development we have get_sosreports tool please refer [1].

[1] https://github.com/gluster/glusto-tests/tree/master/tools/get_sosreports

**Comment by aloganat** [comment]
Hi Barak,

Please acknowledge if this tool [1] satisfies your requirement.
[1] https://github.com/gluster/glusto-tests/tree/master/tools/get_sosreports

Thanks,
Arthy

**Comment by BarakSason** [comment]
Thank you. Will update.

**Comment by BarakSason** [comment]
@aloganat @kshithijiyer 
I have tested the tool and it works well.
One minor issue - During run, the tools prints "/var/tmp/sosreport-vm3-barak-pc-2020-08-12-thweqko.tar.xz", however this is incorrect, as the file was generated in the current directory I was working in.

I do think that this functionality needs to be integrated into the test framework itself (e.g. adding an option to the config file to automatically generate this report) in order to allow a fully automated process (the fact that this tool already exists saves much of the work).

**Comment by kshithijiyer** [comment]
@BarakSason `"/var/tmp/sosreport-vm3-barak-pc-2020-08-12-thweqko.tar.xz"` This is the dir where the on the remote machine where it's sosreport is collected. To check run `sosreport` command on any Linux machine, it'll go to that path by default,

**Comment by kshithijiyer** [comment]
> @aloganat @kshithijiyer
> I have tested the tool and it works well.
> One minor issue - During run, the tools prints "/var/tmp/sosreport-vm3-barak-pc-2020-08-12-thweqko.tar.xz", however this is incorrect, as the file was generated in the current directory I was working in.
> 
> I do think that this functionality needs to be integrated into the test framework itself (e.g. adding an option to the config file to automatically generate this report) in order to allow a fully automated process (the fact that this tool already exists saves much of the work).

We only need sosreports if the testcases is failing due to a genuine bug. Adding this will only slow down the framework.  This looks more like something which is done in the CI and not in the framework.

**Comment by BarakSason** [comment]
@kshithijiyer 
> We only need sosreports if the testcases is failing due to a genuine bug. 
This statement is very limited in it's view. There can be multiple cases in which I'd want logs, even if no failures happened.

>Adding this will only slow down the framework.
The option can be configurable. If you don't want to use it - don't. In this case how will it slow anything down?

>This looks more like something which is done in the CI and not in the framework.
Since the tool that creates the report is already present, which not leverage it from inside the system? Why is an additional external tool needed?

I'd go even one step further and say that granularity is also important.
As it does take time to generate SOS report, and they are many cases when simple logs are sufficient I'd advise to go with 2 options:
1 - Gather full SOS reports
2 - Gather only logs
