### ISSUE TITLE
improve functionality by accepting variable as well

### ISSUE THREAD

**Issue by Sanju-1919** [gluster/glusto-tests#4]
In glusto test cases, we are supposed to pass list of arguments. When we want to pass a single argument if we pass it as a variable instead of list, it is handling the variable as a list.
My suggestion is we can improve the function in such a way that,
it also accepts a variable so that when we want to pass a single argument we can pass
variable instead of list.

We can improve the functionality with the help of "instanceof" in python. We can check whether
the argument is list or not, if not we can convert it into a list.

**Comment by nigelbabu** [comment]
This is now done.
