### ISSUE TITLE
correct logging must be reflected for testcase failure

### ISSUE THREAD

**Issue by nchilaka** [gluster/glusto-tests#5]
while analysing one of the test runs, one test case failed saying it had hit the timeout of 20min, but that was not the case.
Later it was seen that this case failed, because of heal info xml showing one brick down.
We need to wait for more time and recheck for heal info to reflect the changes, instead of failing them at the first failure itself.

I was looking into logs of the failed case "tests.functional.bvt.test_cvt.TestGlusterHealSanity_cplex_distributed-replicated_glusterfs.test_self_heal_when_io_in_progress"
 in http://jenkins-rhs.lab.eng.blr.redhat.com:8080/view/Auto%20RHEL%206.9/job/auto-RHGS_Downstream_BVT_RHEL_6_9_RHGS_3_4_brew/ws/glusto_3.log
It failed with "AssertionError: Self heal didn't complete even after waiting for 20 minutes. 20 minutes is too much a time for current test workload"

However, when I looked into the details, I see that the whole testcase was run only for 2 minutes.

**Comment by nigelbabu** [comment]
Same job fails upstream. See logs attached to this job: https://ci.centos.org/view/Gluster/job/gluster_glusto/441/console
