### ISSUE TITLE
Need contributor guide

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [gluster/glusto-tests#7]
How to contribute to glusto-tests?  

Please update about contributing to glusto-tests in the top level README either inline (or) in separate contributing.md

**Comment by loadtheaccumulator** [comment]
@Akarsha-rai @vavuthu We cover basics on how to write tests in the HOWTO and developer's guide, but need to add the part about the where and how to submit contributions for review.

**Comment by dolanoi** [comment]
A pathc has been submitted for this issue.
https://review.gluster.org/23051

**Comment by dolanoi** [comment]
> A patch has been submitted for this issue.
> https://review.gluster.org/23051

Patch has been merged.
